name: Pipeline!
on:
  push:
    branches:
      - main
jobs:
  lint_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: lint it
        run: npm run eslint
  testinng-job:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    - name: Build
      run: npm run build
    - name: Run Jest tests
      run: npm test
    - name: Run Playwright tests
      run: npm run test:e2e:ui

  