name: hello world!
on:
  push:
      branches: 
      - main
jobs:
  hello_job:
    runs-on: ubuntu-20.04
    steps:
      - name: say_hello    
        run: |
          echo "HELLO WORLD"
          
