name: hello world!
on:
  push:
    branches: 
      - main
jobs:
  date_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Date
        run: date
  ls_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List files
        run: ls -l
  hello_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello    
        run: |
          echo "HELLO WORLD"